language: rust
cache: cargo
script:
- cargo build --release --verbose
- cargo test --release --verbose
before_install:
- openssl aes-256-cbc -K $encrypted_bac4f375afe1_key -iv $encrypted_bac4f375afe1_iv
  -in .travis/boot_roms.tar.enc -out .travis/boot_roms.tar -d
- tar xvf .travis/boot_roms.tar
